version: '2'
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'tuda@123'
    volumes:
      - ./initsql:/docker-entrypoint-initdb.d
  redis:
    image: redis
  zookeeper:
    image: jplock/zookeeper
  disconf:
    image: bailaohe/disconf
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis 
      - zookeeper
  nginx:
    image: nginx
    ports:
      - "9999:9999" 
    volumes:
      - ./disconf/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./html:/html
    depends_on:
      - disconf
